name: Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
        run:
          shell: bash
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.9]
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          mamba-version: "2.0.5"
          channels: conda-forge
          activate-environment: pyemittance-dev
          environment-file: environment-dev.yml
          
#      - name: flake8
#        shell: bash -l {0}
#        run: |
#          flake8 .

      - name: Install PyEmittance
        shell: bash -l {0}
        run: |
          pip install --no-dependencies .

      - name: Run Tests
        shell: bash -l {0}
        run: |
          bash run_tests.bash

      - name: Execute notebooks
        shell: bash -l {0}
        run: |
          bash scripts/execute_notebooks.bash

 #     - name: Run E2E Tests
 #       uses: BerniWittmann/background-server-action@latest
 #       with:
 #         command: pytest tests
 #         start: python tests/start_server.py
